@echo off
setlocal
cd /d "%~dp0"

rem ===== APP_VERSION: change here only, exe filename and in-app version follow =====
set "APP_VERSION=1.0.0"

set "CSC=%WINDIR%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if not exist "%CSC%" set "CSC=%WINDIR%\Microsoft.NET\Framework\v4.0.30319\csc.exe"
if not exist "%CSC%" (
    echo [x] csc.exe not found. .NET Framework 4.x is required.
    pause
    exit /b 1
)

if not exist "app.ico" (
    echo Generating app.ico ...
    powershell -NoProfile -ExecutionPolicy Bypass -File gen-icon.ps1
)

rem Generate VersionInfo.cs from APP_VERSION (shown in the app footer)
> VersionInfo.cs echo // Auto-generated by build.cmd. Edit APP_VERSION in build.cmd instead.
>> VersionInfo.cs echo namespace ShortcutArrow
>> VersionInfo.cs echo {
>> VersionInfo.cs echo     internal static class AppInfo
>> VersionInfo.cs echo     {
>> VersionInfo.cs echo         public const string Version = "%APP_VERSION%";
>> VersionInfo.cs echo     }
>> VersionInfo.cs echo }

echo Building: DesktopIconBeautifier-v%APP_VERSION%.exe ...
"%CSC%" /nologo /target:winexe /platform:anycpu /optimize+ ^
    /out:"..\DesktopIconBeautifier-v%APP_VERSION%.exe" ^
    /win32manifest:app.manifest ^
    /win32icon:app.ico ^
    /resource:blank.ico,blank.ico ^
    /resource:logo64.png,logo64.png ^
    /r:System.dll /r:System.Drawing.dll /r:System.Windows.Forms.dll ^
    /codepage:65001 Program.cs VersionInfo.cs

if errorlevel 1 (
    echo [x] Build failed.
    pause
    exit /b 1
)
echo [OK] Generated: DesktopIconBeautifier-v%APP_VERSION%.exe
pause
